version: 2
jobs:
  build:
    docker:
      - image: cloudmesh/book:1.0
    steps:
      - checkout
      - run:
          name: where
          command: ls; pwd      
      - run:
          name: check syntax
          command: make chars
      - run:
          name: create epub
          command: make > compile.log
  test:
    docker:
       - image: cloudmesh/book:1.0
    steps:
       - run:
          name: log
          command: cat compile.log
       -run:
          name: bibtex issues
          command: fgrep pandoc-citeproc compile.log
       - run:
          name: check syntax
          command: make chars
