version: 2
jobs:
  build:
    docker:
      - image: cloudmesh/book:1.0
    steps:
      - checkout
      - run:
          name: where
          command: ls; pwd
      - run:
          name: create epub
          command: make &> compile.log
      - run:
          name: log
          command: cat compile.log
      - run:
          name: bibtex issues
          command: fgrep pandoc-citeproc compile.log          
      - run:
          name: check syntax
          command: make chars
      - run:
          name: changed files
          command: git diff-tree --no-commit-id --name-only -r HEAD
      - run:
          name: changed files CI
          command: git diff-tree --no-commit-id --name-only -r `echo ${CIRCLE_COMPARE_URL} | cut -d/ -f 7`
  test:
    docker:
      - image: cloudmesh/book:1.0
    steps:
      - run:
          name: check syntax
          command: make chars
