version: 2
jobs:
  build:
    docker:
      - image:  cloudmesh/technologies:1.2
    steps:
      - checkout
      - run:
          name: check
          command: cd technologies; git pull && make chars && make
